import type { StarterData } from "./types";

export const STARTER_DATA: StarterData = {
  companies: [
    {
      id: "deloitte",
      name: "Deloitte",
      role: "Consultant · Client-facing",
      vibe: "Polished business casual — blazers, loafers, quiet luxury",
      sourceEmployeeCount: 2140,
    },
    {
      id: "goldman",
      name: "Goldman Sachs",
      role: "Analyst · NY office",
      vibe: "Tailored suiting, crisp shirts, formal",
      sourceEmployeeCount: 1890,
    },
    {
      id: "mckinsey",
      name: "McKinsey & Co.",
      role: "Business Analyst",
      vibe: "Sharp tailoring, conservative palette, travel-ready",
      sourceEmployeeCount: 960,
    },
    {
      id: "stripe",
      name: "Stripe",
      role: "Product Manager",
      vibe: "Elevated casual — knit polos, trousers, clean sneakers",
      sourceEmployeeCount: 720,
    },
    {
      id: "google",
      name: "Google",
      role: "APM",
      vibe: "Smart casual — soft tailoring, no suits",
      sourceEmployeeCount: 12400,
    },
    {
      id: "meta",
      name: "Meta",
      role: "Product Designer",
      vibe: "Casual with intention — tees, denim, a nice jacket",
      sourceEmployeeCount: 6800,
    },
    {
      id: "law",
      name: "Corporate law firm",
      role: "Associate · NYC",
      vibe: "Conservative suiting, minimal accessories, court-ready polish",
      sourceEmployeeCount: 420,
    },
    {
      id: "healthcare",
      name: "Academic health system",
      role: "Attending physician",
      vibe: "Clinical layers, business casual off the floor, comfortable shoes",
      sourceEmployeeCount: 1580,
    },
    {
      id: "marketing_pr",
      name: "Global agency network",
      role: "Account director",
      vibe: "Statement pieces on pitch days, smart casual day-to-day, strong personal brand",
      sourceEmployeeCount: 890,
    },
    {
      id: "media",
      name: "National newsroom",
      role: "Senior editor",
      vibe: "Understated neutrals, field-ready when reporting, newsroom casual in office",
      sourceEmployeeCount: 1120,
    },
    {
      id: "nonprofit_gov",
      name: "Civil service / nonprofit",
      role: "Policy lead",
      vibe: "Approachable professional dress, low flash, versatile layering for community meetings",
      sourceEmployeeCount: 540,
    },
    {
      id: "education",
      name: "Research university",
      role: "Faculty & admin",
      vibe: "Faculty varies by department — tailored on teaching days, relaxed office hours",
      sourceEmployeeCount: 2310,
    },
    {
      id: "startups_creative",
      name: "Seed-stage startup",
      role: "Founding designer",
      vibe: "Creative studio casual — intentional basics, one hero piece, sneakers welcome",
      sourceEmployeeCount: 180,
    },
  ],

  items: [
    {
      id: 1,
      brand: "Franco Sarto",
      name: "Rue Pointed Mule",
      category: "Shoes",
      retail: 120,
      price: 198,
      resale: true,
      source: "Depop",
      condition: "Good · light wear",
      tone: "#c4b5a0",
    },
    {
      id: 2,
      brand: "Madewell",
      name: "Medium Transport Tote",
      category: "Bag",
      retail: 168,
      price: 135,
      resale: false,
      source: "madewell.com",
      tone: "#6b4e3d",
    },
    {
      id: 3,
      brand: "Babaton",
      name: "Power Blazer",
      category: "Outerwear",
      retail: 228,
      price: 42,
      resale: true,
      source: "Poshmark",
      condition: "Like new",
      tone: "#e8e8e8",
    },
    {
      id: 4,
      brand: "Stuart Weitzman",
      name: "City Slouch Boot",
      category: "Shoes",
      retail: 695,
      price: 289,
      resale: true,
      source: "The RealReal",
      condition: "Excellent",
      tone: "#1a1a1a",
    },
    {
      id: 5,
      brand: "COS",
      name: "Slouch Leather Shopper",
      category: "Bag",
      retail: 189,
      price: 58,
      resale: true,
      source: "Depop",
      condition: "Good · light wear",
      tone: "#c9b8a4",
    },
    {
      id: 6,
      brand: "Everlane",
      name: "Way-High Drape Pant",
      category: "Bottom",
      retail: 128,
      price: 128,
      resale: false,
      source: "everlane.com",
      tone: "#f2f2f2",
    },
    {
      id: 7,
      brand: "Halogen",
      name: "Ribbed Button Cardigan",
      category: "Top",
      retail: 69,
      price: 68,
      resale: true,
      source: "The RealReal",
      condition: "Excellent",
      tone: "#fafafa",
    },
    {
      id: 8,
      brand: "AGOLDE",
      name: "Ren Long Sleeve Tee",
      category: "Top",
      retail: 108,
      price: 95,
      resale: false,
      source: "agolde.com",
      tone: "#f0ece3",
    },
    {
      id: 9,
      brand: "Skims",
      name: "Fits Everybody Bodysuit",
      category: "Top",
      retail: 62,
      price: 62,
      resale: false,
      source: "skims.com",
      tone: "#f7f5f2",
    },
    {
      id: 10,
      brand: "Halogen",
      name: "Wrap Front Shell",
      category: "Top",
      retail: 59,
      price: 58,
      resale: false,
      source: "nordstrom.com",
      tone: "#ffffff",
    },
    {
      id: 11,
      brand: "Naadam",
      name: "Cashmere Wrap",
      category: "Outerwear",
      retail: 185,
      price: 78,
      resale: true,
      source: "The RealReal",
      condition: "Good",
      tone: "#d9d0c4",
    },
    {
      id: 12,
      brand: "Sam Edelman",
      name: "Laguna Chelsea Boot",
      category: "Shoes",
      retail: 170,
      price: 128,
      resale: false,
      source: "samedelman.com",
      tone: "#3a2f28",
    },
  ],

  outfits: [
    { day: "Day 1", note: "First impressions", items: [1, 3, 6, 2] },
    { day: "Client meeting", note: "Polished", items: [1, 10, 6, 2, 9] },
    { day: "Team drinks", note: "Off-duty", items: [7, 6, 5] },
    { day: "Travel day", note: "Airport to office", items: [4, 7, 11, 5] },
    { day: "Friday", note: "Dress-down", items: [8, 6, 5, 12] },
    { day: "All-hands", note: "Low-key sharp", items: [10, 11, 5, 12] },
    { day: "Happy hour", note: "After work", items: [3, 2, 10, 9] },
    { day: "Rainy Monday", note: "Layered", items: [4, 10, 11, 5] },
  ],

  vibes: [
    { id: "minimal", label: "Minimal", note: "The Row, COS, quiet luxury" },
    { id: "editorial", label: "Editorial", note: "Vogue, Totême, confident" },
    { id: "preppy", label: "Preppy", note: "J.Crew, classic, collegiate" },
  ],

  quiz: [
    {
      q: "Which room is more you?",
      a: {
        label: "Plaster + oak",
        hint: "neutral, warm, quiet",
        image: "/quiz/plaster-oak.png",
      },
      b: {
        label: "Steel + glass",
        hint: "crisp, modern, cool",
        image: "/quiz/steel-glass.png",
      },
      c: {
        label: "Linen + stone",
        hint: "airy, soft light, calm",
        image: "/quiz/linen-stone.png",
      },
      d: {
        label: "Velvet + brass",
        hint: "moody, layered, evening",
        image: "/quiz/velvet-brass.png",
      },
    },
    {
      q: "Which silhouette?",
      a: {
        label: "Relaxed trouser",
        hint: "softer shoulders",
        image: "/quiz/relaxed-trouser.png",
      },
      b: {
        label: "Sharp tailoring",
        hint: "defined waist",
        image: "/quiz/sharp-tailoring.png",
      },
      c: {
        label: "Column line",
        hint: "long, minimal break",
        image: "/quiz/column-line.png",
      },
      d: {
        label: "Boxy layer",
        hint: "structure, no cinch",
        image: "/quiz/boxy-layer.png",
      },
    },
    {
      q: "Which finish?",
      a: { label: "Matte leather", hint: "unfussy, lived-in", image: "/quiz/matte-leather.png" },
      b: { label: "Polished gold", hint: "considered, a little louder", image: "/quiz/polished-gold.png" },
      c: { label: "Brushed silver", hint: "cool, quiet shine", image: "/quiz/brushed-silver.png" },
      d: { label: "Patina bronze", hint: "organic, imperfect warmth", image: "/quiz/patina-bronze.png" },
    },
  ],
};
