import type { StarterData } from "./types";

export const STARTER_DATA: StarterData = {
  companies: [
    {
      id: "deloitte",
      name: "Deloitte",
      role: "Consultant · Client-facing",
      vibe: "Polished business casual — blazers, loafers, quiet luxury",
    },
    {
      id: "goldman",
      name: "Goldman Sachs",
      role: "Analyst · NY office",
      vibe: "Tailored suiting, crisp shirts, formal",
    },
    {
      id: "mckinsey",
      name: "McKinsey & Co.",
      role: "Business Analyst",
      vibe: "Sharp tailoring, conservative palette, travel-ready",
    },
    {
      id: "stripe",
      name: "Stripe",
      role: "Product Manager",
      vibe: "Elevated casual — knit polos, trousers, clean sneakers",
    },
    {
      id: "google",
      name: "Google",
      role: "APM",
      vibe: "Smart casual — soft tailoring, no suits",
    },
    {
      id: "meta",
      name: "Meta",
      role: "Product Designer",
      vibe: "Casual with intention — tees, denim, a nice jacket",
    },
  ],

  items: [
    {
      id: 1,
      brand: "Theory",
      name: "Good Wool Blazer",
      category: "Outerwear",
      retail: 495,
      price: 198,
      resale: true,
      source: "The RealReal",
      condition: "Excellent · worn once",
      tone: "#2a2d3a",
    },
    {
      id: 2,
      brand: "COS",
      name: "Relaxed Trouser",
      category: "Bottom",
      retail: 135,
      price: 135,
      resale: false,
      source: "cos.com",
      tone: "#1a1a1a",
    },
    {
      id: 3,
      brand: "Everlane",
      name: "Silk Shell",
      category: "Top",
      retail: 98,
      price: 42,
      resale: true,
      source: "Poshmark",
      condition: "Like new",
      tone: "#e8e0d2",
    },
    {
      id: 4,
      brand: "Theory",
      name: "Double-Face Coat",
      category: "Outerwear",
      retail: 695,
      price: 289,
      resale: true,
      source: "The RealReal",
      condition: "Excellent",
      tone: "#c9bfae",
    },
    {
      id: 5,
      brand: "Sam Edelman",
      name: "Loraine Loafer",
      category: "Shoes",
      retail: 140,
      price: 58,
      resale: true,
      source: "Depop",
      condition: "Good · light wear",
      tone: "#1c1c1c",
    },
    {
      id: 6,
      brand: "Madewell",
      name: "Perfect Vintage Jean",
      category: "Bottom",
      retail: 128,
      price: 128,
      resale: false,
      source: "madewell.com",
      tone: "#3a4a65",
    },
    {
      id: 7,
      brand: "Reformation",
      name: "Cashmere Crew",
      category: "Top",
      retail: 178,
      price: 68,
      resale: true,
      source: "The RealReal",
      condition: "Excellent",
      tone: "#d9d2c4",
    },
    {
      id: 8,
      brand: "Vince",
      name: "Essential Tee",
      category: "Top",
      retail: 95,
      price: 95,
      resale: false,
      source: "vince.com",
      tone: "#f0ece3",
    },
    {
      id: 9,
      brand: "Polène",
      name: "Numéro Un Nano",
      category: "Bag",
      retail: 560,
      price: 560,
      resale: false,
      source: "polene-paris.com",
      tone: "#2e2a24",
    },
    {
      id: 10,
      brand: "J.Crew",
      name: "Tissue Turtleneck",
      category: "Top",
      retail: 58,
      price: 58,
      resale: false,
      source: "jcrew.com",
      tone: "#1a1a1a",
    },
    {
      id: 11,
      brand: "Agolde",
      name: "Riley Straight",
      category: "Bottom",
      retail: 198,
      price: 78,
      resale: true,
      source: "The RealReal",
      condition: "Good",
      tone: "#22262e",
    },
    {
      id: 12,
      brand: "Mejuri",
      name: "Bold Hoops (small)",
      category: "Accessory",
      retail: 128,
      price: 128,
      resale: false,
      source: "mejuri.com",
      tone: "#b89a5e",
    },
  ],

  outfits: [
    { day: "Day 1", note: "First impressions", items: [1, 3, 2, 5] },
    { day: "Client meeting", note: "Polished", items: [1, 10, 2, 5, 9] },
    { day: "Team drinks", note: "Off-duty", items: [7, 6, 5] },
    { day: "Travel day", note: "Airport to office", items: [4, 7, 11, 5] },
    { day: "Friday", note: "Dress-down", items: [8, 6, 5, 12] },
    { day: "All-hands", note: "Low-key sharp", items: [10, 11, 5, 12] },
    { day: "Happy hour", note: "After work", items: [3, 2, 5, 9] },
    { day: "Rainy Monday", note: "Layered", items: [4, 10, 11, 5] },
  ],

  vibes: [
    { id: "minimal", label: "Minimal", note: "The Row, COS, quiet luxury" },
    { id: "editorial", label: "Editorial", note: "Vogue, Totême, confident" },
    { id: "preppy", label: "Preppy", note: "J.Crew, classic, collegiate" },
  ],

  quiz: [
    {
      q: "Which room is more you?",
      a: { label: "Plaster + oak", hint: "neutral, warm, quiet" },
      b: { label: "Steel + glass", hint: "crisp, modern, cool" },
    },
    {
      q: "Which silhouette?",
      a: { label: "Relaxed trouser", hint: "softer shoulders" },
      b: { label: "Sharp tailoring", hint: "defined waist" },
    },
    {
      q: "Which finish?",
      a: { label: "Matte leather", hint: "unfussy, lived-in" },
      b: { label: "Polished gold", hint: "considered, a little louder" },
    },
  ],
};
